sbt-build = [
  "ch.epfl.scala:sbt-scalafix:0.14.6:sbt-plugin"
  "ch.epfl.scala:sbt-version-policy:3.2.1:sbt-plugin"
  "com.alejandrohdezma:sbt-ci:3.0.0:sbt-plugin"
  "com.alejandrohdezma:sbt-github-header:0.13.0:sbt-plugin"
  "com.alejandrohdezma:sbt-github-mdoc:0.13.0:sbt-plugin"
  "com.alejandrohdezma:sbt-modules:0.4.1:sbt-plugin"
  "com.alejandrohdezma:sbt-scalafix-defaults:0.15.0:sbt-plugin"
  "com.alejandrohdezma:sbt-scalafmt-defaults:0.10.0:sbt-plugin"
  "com.github.sbt:sbt-ci-release:1.11.2:sbt-plugin"
  "com.github.sbt:sbt-header:5.11.0:sbt-plugin"
  "org.scalameta:sbt-mdoc:2.8.2:sbt-plugin"
  "org.scalameta:sbt-scalafmt:2.5.6:sbt-plugin"
  "org.typelevel:sbt-tpolecat:0.5.3:sbt-plugin"
]
