addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"   % "0.9.11")
addSbtPlugin("com.alejandrohdezma"       % "sbt-me"         % "0.3.0")
addSbtPlugin("com.geirsson"              % "sbt-ci-release" % "1.4.31")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"   % "0.1.10")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"       % "2.0.3")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"   % "2.2.1")
